# clocks.yml
# docker stack deploy -c clocks.yml lotsofclocks

version: "3"

services:
  clock:
    image: clock_app:latest
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
